// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Secret defines model for Secret.
type Secret struct {
	// EncryptedData AES-256 encrypted payload
	EncryptedData string             `json:"encrypted_data"`
	Id            openapi_types.UUID `json:"id"`
	Label         *string            `json:"label,omitempty"`
}

// UserAuth defines model for UserAuth.
type UserAuth struct {
	// PasswordHash Client-side derived hash of the master password
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
}

// PostApiV1AuthRegisterJSONRequestBody defines body for PostApiV1AuthRegister for application/json ContentType.
type PostApiV1AuthRegisterJSONRequestBody = UserAuth

// PostApiV1VaultJSONRequestBody defines body for PostApiV1Vault for application/json ContentType.
type PostApiV1VaultJSONRequestBody = Secret

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register a new user
	// (POST /api/v1/auth/register)
	PostApiV1AuthRegister(w http.ResponseWriter, r *http.Request)
	// Get all secrets
	// (GET /api/v1/vault)
	GetApiV1Vault(w http.ResponseWriter, r *http.Request)
	// Store a new secret
	// (POST /api/v1/vault)
	PostApiV1Vault(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register a new user
// (POST /api/v1/auth/register)
func (_ Unimplemented) PostApiV1AuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all secrets
// (GET /api/v1/vault)
func (_ Unimplemented) GetApiV1Vault(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Store a new secret
// (POST /api/v1/vault)
func (_ Unimplemented) PostApiV1Vault(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiV1AuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1AuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1AuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1Vault operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Vault(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Vault(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Vault operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Vault(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Vault(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/register", wrapper.PostApiV1AuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/vault", wrapper.GetApiV1Vault)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/vault", wrapper.PostApiV1Vault)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUX2/bNhD/KsRtj4olJ9sQ6M0btizDCgR1mwINjIAWzxZTimSPJ6dCoO9ekPKfOAqa",
	"NugbTd8df/9OD1C5xjuLlgOUDxCqGhuZjnOsCDmePDmPxBrTPdqKOs+obpVkGW8Uhoq0Z+0slDD7e35y",
	"+vsfYl8nvOyMkwoy4M4jlBCYtF1Dn4FWccDKUSMZSmhb/WyZkUs06fEvsvEm/nnRSG3ErKpca3nc02dA",
	"+LnVhArKG0hjnyBf7Jvc8g4rjg+9D0izlusxbS9DuHekbmsZ6jHrv4xGyydBKxQKSW9QiVgp3EpwjaKR",
	"gZHEbspzJNuAZGWDcfi32ewrsyewxpT6DAJWLWnu5tHbgcwSJR2IDr/+2Znw34d3kA1JiJOGfw+Aa2YP",
	"fRys7cqNlfiI5E4+WXdvUK1RXG0BijfSyjWSmF1dTsS/0iqD4VFIlsYtg3DWdJP4lubk8jxix2vZGo6N",
	"kMEGKQwPTSfFpIjCOY9Weg0lnE2KyVlShetENJde55tpLluuc8K1ji4kO11I2Y4Wy4j8UkEJVy7wzOvr",
	"aZTm7a58EB8D/+lUF5sqZxlt6pfeG12lCfldiLh2SxRPvxKuoIRf8sOW5dsVy/dR64/tZWoxXQTvbBj8",
	"Oi2mY6HjAFERSkYVZfitKMZF19JoleAJJHI0JKJtGkkdlLDjKKSweC9isFLFTrdNVD5OXeMzcl3goFby",
	"B0aYix/SSjM24SXRth+lfp9GSSS7QcJj4v/rwHH5DgkLqTcc7QSUN8fbcLPoF48FukAW0phDc/ZSdA5i",
	"/PzM7Oi/MjFD+ysz872KzdkRbvMUHuENSHF3U/8Tq1wljVC4QeN8g5bFUAsZtGS2n5wyz02sq13g8rw4",
	"L3LoF/3XAAAA//8C/tSdwAYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
